### ISSUE TITLE
Issue loading speech model into docker.

### ISSUE THREAD

**Issue by correlator** [zelo/deepspeech-rest-api#1]
Steps to reproduce:
1. Clone repo
2. Download pbmm model from 0.7.1 release and put in root directory
![Screen Shot 2020-06-18 at 9 43 54 AM](https://user-images.githubusercontent.com/5183236/85048493-3ac56c80-b148-11ea-8009-0dfbe0f9b850.png)
3.  docker-compose up.

![Screen Shot 2020-06-18 at 9 44 23 AM](https://user-images.githubusercontent.com/5183236/85048534-4ca70f80-b148-11ea-9b8d-aabbe7556512.png)

**Comment by zelo** [comment]
@correlator 
The problem is caused by invalid reference in docker-compose.yml
```
    volumes:
      - './model:/app/model:ro'
```
should be
```
    volumes:
      - '/model.pbmm:/app/model.pbmm:ro'
```
Should be already fixed.
