### ISSUE TITLE
How to get JSON output?

### ISSUE THREAD

**Issue by Ajayrajpurohit** [zelo/deepspeech-rest-api#3]
The transcript right now only sends out a long string. But on the same model I have tested manually with the --json flag and it gave time-slots word by word. Is it possible to do it in this REST API??

**Comment by zelo** [comment]
I'm not sure right now what --json flags triggers in deepspeech cli client but I would start by replacing invocation of `stt` method with `sttWithMetadata` here https://github.com/zelo/deepspeech-rest-api/blob/fc1842a6ae87d3e30be009cde8eb5003964ff851/stt/engine.py#L27 . This may also require casting resulting `Metadata` objects to json.
More details here: https://deepspeech.readthedocs.io/en/latest/Python-API.html#native_client.python.Model.sttWithMetadata

**Comment by Ajayrajpurohit** [comment]
Thanks, Dude (@zelo)!!

I have created a pull request after implementing some functional changes ([Pull 4](https://github.com/zelo/deepspeech-rest-api/pull/4)). Please do a review and if you can help me get the JSON Object as a response it'll be great. Have a Nice Day!
